/* ═══════════════════════════════════════════════════════════
   CHRISTIAN LIU — GAME SITE  main.js
   Config-driven. Edit config.js — do not edit this file.
   Translations live in i18n.js — do not hardcode strings here.
════════════════════════════════════════════════════════════ */

/* ── Nav scroll ──────────────────────────────────────────── */
(function () {
  const nav = document.getElementById('nav');
  window.addEventListener('scroll', () => {
    nav.classList.toggle('scrolled', window.scrollY > 40);
  }, { passive: true });
})();

/* ── Scroll reveal ───────────────────────────────────────── */
function initReveal() {
  const observer = new IntersectionObserver((entries) => {
    entries.forEach((entry) => {
      if (!entry.isIntersecting) return;
      const delay = entry.target.closest('.track-list')
        ? Array.from(entry.target.parentElement.children).indexOf(entry.target) * 60
        : 0;
      setTimeout(() => entry.target.classList.add('visible'), delay);
      observer.unobserve(entry.target);
    });
  }, { threshold: 0.12, rootMargin: '0px 0px -48px 0px' });
  document.querySelectorAll('.reveal, .fade-in').forEach(el => observer.observe(el));
  return observer;
}
const revealObserver = initReveal();

/* ── Video section ───────────────────────────────────────── */
(function () {
  const videos  = SITE_CONFIG.VIDEOS || [];
  const section = document.getElementById('videoSection');
  if (!section) return;
  if (!videos.length) { section.style.display = 'none'; return; }
  section.style.display = '';

  function makeEmbed(vid, large) {
    const wrap = document.createElement('div');
    wrap.className = large ? 'video-featured reveal' : 'video-card reveal';
    wrap.innerHTML = `
      <div class="video-thumb-wrap">
        <img class="video-thumb"
             src="https://i.ytimg.com/vi/${vid.youtubeId}/maxresdefault.jpg"
             alt="${vid.title || ''}" loading="lazy"/>
        <button class="video-play-overlay" aria-label="Play ${vid.title || 'video'}">
          <svg width="56" height="56" viewBox="0 0 56 56" fill="none" aria-hidden="true">
            <circle cx="28" cy="28" r="28" fill="rgba(249,86,79,0.92)"/>
            <polygon points="22,18 42,28 22,38" fill="#fff"/>
          </svg>
        </button>
      </div>
      ${vid.title ? `<p class="video-title">${vid.title}</p>` : ''}
      ${vid.desc  ? `<p class="video-desc">${vid.desc}</p>`   : ''}
    `;
    wrap.querySelector('.video-play-overlay').addEventListener('click', () => {
      const iframe = document.createElement('iframe');
      iframe.src = `https://www.youtube-nocookie.com/embed/${vid.youtubeId}?autoplay=1&rel=0`;
      iframe.title = vid.title || 'Video';
      iframe.allow = 'accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture';
      iframe.allowFullscreen = true;
      iframe.className = 'video-iframe';
      wrap.querySelector('.video-thumb-wrap').replaceWith(iframe);
    });
    return wrap;
  }

  const featured = videos.filter(v => v.featured);
  const extras   = videos.filter(v => !v.featured);
  const inner    = section.querySelector('.video-inner');
  if (featured.length) inner.appendChild(makeEmbed(featured[0], true));
  if (extras.length) {
    const row = document.createElement('div');
    row.className = 'video-cards-row';
    extras.forEach(v => row.appendChild(makeEmbed(v, false)));
    inner.appendChild(row);
  }
  inner.querySelectorAll('.reveal').forEach(el => revealObserver.observe(el));
})();

/* ── Waveform player ─────────────────────────────────────── */
(function () {
  const TRACKS = SITE_CONFIG.TRACKS || [];
  if (!TRACKS.length) return;

  const listEl       = document.getElementById('trackList');
  const playerEl     = document.getElementById('player');
  const titleEl      = document.getElementById('playerTitle');
  const metaEl       = document.getElementById('playerMeta');
  const numEl        = document.getElementById('playerTrackNum');
  const durationEl   = document.getElementById('playerDuration');
  const currentTimeEl= document.getElementById('playerCurrentTime');
  const progressEl   = document.getElementById('playerProgress');
  const fillEl       = document.getElementById('playerProgressFill');
  const thumbEl      = document.getElementById('playerProgressThumb');
  const playPauseBtn = document.getElementById('playerPlayPause');
  const prevBtn      = document.getElementById('playerPrev');
  const nextBtn      = document.getElementById('playerNext');
  const canvas       = document.getElementById('waveformCanvas');
  const wCtx         = canvas && canvas.getContext('2d');

  /* ── Real audio element ── */
  const audioEl = new Audio();
  audioEl.preload = 'metadata';

  /* ── State ── */
  let currentIndex = -1;
  let isPlaying    = false;
  let rafId        = null;

  /* ── Build track item HTML ── */
  function buildTrackItem(track, i, lang) {
    const { gameLabel, genreLabel } = tTrack(track, lang);

    // Game name: link if gameUrl provided, plain text otherwise
    const gameHtml = track.gameUrl
      ? `<a href="${track.gameUrl}" target="_blank" rel="noopener noreferrer" class="track-game-link">${gameLabel} ↗</a>`
      : gameLabel;

    const item = document.createElement('article');
    item.className = 'track-item reveal';
    item.setAttribute('role', 'listitem');
    item.setAttribute('data-track', i);
    item.innerHTML = `
      <div class="track-num">${String(i + 1).padStart(2, '0')}</div>
      <div class="track-info">
        <h3 class="track-name">${track.title}</h3>
        <p class="track-meta"><span class="track-game">${gameHtml}</span>&nbsp;·&nbsp;<span class="track-genre-label">${genreLabel}</span></p>
      </div>
      <div class="track-duration">${track.durationStr}</div>
      <button class="track-play-btn" aria-label="Play ${track.title}">
        <svg class="icon-play" width="20" height="20" viewBox="0 0 24 24" fill="currentColor"><polygon points="5,3 19,12 5,21"/></svg>
        <svg class="icon-pause" width="20" height="20" viewBox="0 0 24 24" fill="currentColor" style="display:none"><rect x="6" y="4" width="4" height="16"/><rect x="14" y="4" width="4" height="16"/></svg>
      </button>
    `;
    return item;
  }

  /* ── Render / re-render track list (called on init + language switch) ── */
  function renderTracks(lang) {
    if (!listEl) return;
    const wasActive = currentIndex;
    listEl.innerHTML = '';
    TRACKS.forEach((track, i) => {
      const item = buildTrackItem(track, i, lang);
      if (i === wasActive) item.classList.add('active');
      listEl.appendChild(item);
      // Re-attach click
      item.addEventListener('click', (e) => {
        if (e.target.closest('a')) return; // don't hijack link clicks
        if (currentIndex === i) { isPlaying ? pause() : play(); }
        else { loadTrack(i); play(); }
      });
    });
    listEl.querySelectorAll('.reveal').forEach(el => revealObserver.observe(el));
    updatePlayPauseUI();
  }

  // Expose for i18n.js to call on language switch
  window.__renderTracks = renderTracks;

  /* ── Update player bar meta on language switch ── */
  window.__updatePlayerMeta = function (lang) {
    if (currentIndex < 0) return;
    const track = TRACKS[currentIndex];
    const { gameLabel, genreLabel } = tTrack(track, lang);
    if (metaEl) metaEl.textContent = `${gameLabel} · ${genreLabel}`;
  };

  /* ── Waveform ── */
  const BAR_COUNT = 80;
  let waveformData = [];

  function generateWaveform(seed) {
    const data = []; let rng = seed * 9301 + 49297;
    for (let i = 0; i < BAR_COUNT; i++) {
      rng = (rng * 9301 + 49297) % 233280;
      data.push((rng / 233280) * (Math.sin((i / BAR_COUNT) * Math.PI) * 0.7 + 0.3));
    }
    return data;
  }

  function drawWaveform(progress) {
    if (!wCtx || !canvas) return;
    const dpr = window.devicePixelRatio || 1;
    if (canvas.width  !== Math.round(canvas.offsetWidth  * dpr) ||
        canvas.height !== Math.round(canvas.offsetHeight * dpr)) {
      canvas.width  = Math.round(canvas.offsetWidth  * dpr);
      canvas.height = Math.round(canvas.offsetHeight * dpr);
      wCtx.scale(dpr, dpr);
    }
    const w = canvas.offsetWidth, h = canvas.offsetHeight;
    wCtx.clearRect(0, 0, canvas.width, canvas.height);
    const barW = (w / BAR_COUNT) * 0.55, gapW = (w / BAR_COUNT) * 0.45;
    const style = getComputedStyle(document.documentElement);
    const accentColor = style.getPropertyValue('--color-primary').trim() || '#F9564F';
    const mutedColor  = style.getPropertyValue('--color-text-faint').trim() || 'rgba(243,198,119,0.38)';
    for (let i = 0; i < BAR_COUNT; i++) {
      const x    = i * (barW + gapW);
      const barH = Math.max(3, waveformData[i] * h * 0.92);
      const y    = (h - barH) / 2;
      const barP = i / BAR_COUNT;
      const prox = Math.abs(barP - progress);
      const pulse = isPlaying && prox < 0.04 ? 1 + (0.04 - prox) * 4 : 1;
      wCtx.beginPath();
      if (wCtx.roundRect) wCtx.roundRect(x, y - (pulse - 1) * barH * 0.2, barW, barH * pulse, 2);
      else wCtx.rect(x, y, barW, barH);
      wCtx.fillStyle = barP <= progress ? accentColor : mutedColor;
      wCtx.globalAlpha = 1;
      wCtx.fill();
    }
    wCtx.globalAlpha = 1;
  }

  function formatTime(s) {
    if (!isFinite(s) || s < 0) return '0:00';
    return `${Math.floor(s / 60)}:${String(Math.floor(s % 60)).padStart(2, '0')}`;
  }

  /* ── RAF tick — syncs UI to real audioEl.currentTime ── */
  function tick() {
    if (!isPlaying) return;
    const total    = audioEl.duration || TRACKS[currentIndex]?.duration || 1;
    const cur      = audioEl.currentTime;
    const progress = Math.max(0, Math.min(1, cur / total));
    if (currentTimeEl) currentTimeEl.textContent = formatTime(cur);
    if (fillEl)        fillEl.style.width         = `${progress * 100}%`;
    if (thumbEl)       thumbEl.style.left          = `${progress * 100}%`;
    if (progressEl)    progressEl.setAttribute('aria-valuenow', Math.round(progress * 100));
    drawWaveform(progress);
    rafId = requestAnimationFrame(tick);
  }

  /* ── Load track ── */
  function loadTrack(index) {
    if (index < 0 || index >= TRACKS.length) return;
    const track = TRACKS[index];

    audioEl.pause();
    cancelAnimationFrame(rafId);
    isPlaying = false;
    currentIndex = index;
    waveformData = generateWaveform(index + 1);

    // Update list selection
    document.querySelectorAll('.track-item').forEach((el, i) => {
      el.classList.toggle('active', i === index);
      el.querySelector('.icon-play')?.style.setProperty('display', '');
      el.querySelector('.icon-pause')?.style.setProperty('display', 'none');
    });

    // Update player bar
    const lang = getCurrentLang();
    const { gameLabel, genreLabel } = tTrack(track, lang);
    if (titleEl)       titleEl.textContent       = track.title;
    if (metaEl)        metaEl.textContent         = `${gameLabel} · ${genreLabel}`;
    if (numEl)         numEl.textContent          = String(index + 1).padStart(2, '0');
    if (durationEl)    durationEl.textContent     = track.durationStr;
    if (currentTimeEl) currentTimeEl.textContent  = '0:00';
    if (fillEl)        fillEl.style.width         = '0%';
    if (thumbEl)       thumbEl.style.left         = '0%';
    if (playerEl)      playerEl.classList.add('visible');

    audioEl.src         = track.src || '';
    audioEl.currentTime = 0;
    drawWaveform(0);
  }

  /* ── Play / pause ── */
  function play() {
    if (currentIndex < 0) loadTrack(0);
    if (!audioEl.src) return;
    const p = audioEl.play();
    if (p !== undefined) p.catch(err => console.warn('Audio play failed:', err));
    isPlaying = true;
    cancelAnimationFrame(rafId);
    rafId = requestAnimationFrame(tick);
    updatePlayPauseUI();
  }

  function pause() {
    audioEl.pause();
    isPlaying = false;
    cancelAnimationFrame(rafId);
    updatePlayPauseUI();
  }

  /* ── Audio events ── */
  audioEl.addEventListener('loadedmetadata', () => {
    if (currentIndex < 0 || !isFinite(audioEl.duration)) return;
    TRACKS[currentIndex].duration = audioEl.duration;
    if (durationEl) durationEl.textContent = formatTime(audioEl.duration);
  });
  audioEl.addEventListener('ended', () => {
    loadTrack((currentIndex + 1) % TRACKS.length);
    play();
  });
  audioEl.addEventListener('error', () => {
    console.warn('Audio error on track:', TRACKS[currentIndex]?.title, audioEl.error?.message);
  });

  /* ── UI state ── */
  function updatePlayPauseUI() {
    if (!playPauseBtn) return;
    playPauseBtn.querySelector('.icon-play')?.style.setProperty('display', isPlaying ? 'none' : '');
    playPauseBtn.querySelector('.icon-pause')?.style.setProperty('display', isPlaying ? '' : 'none');
    playPauseBtn.setAttribute('aria-label', isPlaying ? 'Pause' : 'Play');
    document.querySelectorAll('.track-item').forEach((el, i) => {
      el.querySelector('.icon-play')?.style.setProperty('display', i === currentIndex && isPlaying ? 'none' : '');
      el.querySelector('.icon-pause')?.style.setProperty('display', i === currentIndex && isPlaying ? '' : 'none');
    });
  }

  /* ── Controls ── */
  playPauseBtn?.addEventListener('click', (e) => {
    e.stopPropagation();
    if (currentIndex === -1) { loadTrack(0); play(); return; }
    isPlaying ? pause() : play();
  });
  prevBtn?.addEventListener('click', (e) => {
    e.stopPropagation();
    loadTrack(currentIndex <= 0 ? TRACKS.length - 1 : currentIndex - 1);
    play();
  });
  nextBtn?.addEventListener('click', (e) => {
    e.stopPropagation();
    loadTrack((currentIndex + 1) % TRACKS.length);
    play();
  });

  /* ── Scrubbing ── */
  let scrubbing = false;
  function getScrubP(e) {
    const r = progressEl.getBoundingClientRect();
    return Math.max(0, Math.min(1, ((e.touches ? e.touches[0].clientX : e.clientX) - r.left) / r.width));
  }
  function scrubTo(p) {
    const total = audioEl.duration || TRACKS[currentIndex]?.duration || 0;
    if (!total || currentIndex < 0) return;
    audioEl.currentTime = p * total;
    if (fillEl) fillEl.style.width = `${p * 100}%`;
    if (thumbEl) thumbEl.style.left = `${p * 100}%`;
    if (currentTimeEl) currentTimeEl.textContent = formatTime(p * total);
    drawWaveform(p);
  }
  progressEl?.addEventListener('mousedown',  (e) => { if (currentIndex < 0) return; scrubbing = true; scrubTo(getScrubP(e)); });
  progressEl?.addEventListener('touchstart', (e) => { if (currentIndex < 0) return; scrubbing = true; scrubTo(getScrubP(e)); }, { passive: true });
  window.addEventListener('mousemove', (e) => { if (scrubbing && currentIndex >= 0) scrubTo(getScrubP(e)); });
  window.addEventListener('mouseup',  () => { scrubbing = false; });
  window.addEventListener('touchend', () => { scrubbing = false; });

  /* ── Keyboard ── */
  document.addEventListener('keydown', (e) => {
    if (!playerEl?.classList.contains('visible')) return;
    if (['INPUT', 'TEXTAREA'].includes(document.activeElement.tagName)) return;
    if (e.code === 'Space')      { e.preventDefault(); isPlaying ? pause() : play(); }
    if (e.code === 'ArrowRight') { loadTrack((currentIndex + 1) % TRACKS.length); play(); }
    if (e.code === 'ArrowLeft')  { loadTrack(currentIndex <= 0 ? TRACKS.length - 1 : currentIndex - 1); play(); }
  });

  /* ── Resize ── */
  window.addEventListener('resize', () => {
    if (currentIndex >= 0) drawWaveform(audioEl.currentTime / (audioEl.duration || 1));
  }, { passive: true });

  /* ── Initial render ── */
  renderTracks(getCurrentLang());
  drawWaveform(0);
})();

/* ── GSAP animations ─────────────────────────────────────── */
window.addEventListener('load', () => {
  if (typeof gsap === 'undefined') return;
  gsap.registerPlugin(ScrollTrigger);
  gsap.from('.hero-name .name-line', { y: 60, opacity: 0, duration: 1.1, stagger: 0.12, ease: 'power3.out', delay: 0.2, clearProps: 'all' });
  gsap.utils.toArray('.section-title').forEach(el => {
    gsap.from(el, { scrollTrigger: { trigger: el, start: 'top 85%' }, y: 40, opacity: 0, duration: 0.9, ease: 'power3.out', clearProps: 'all' });
  });
  gsap.from('.service-card', { scrollTrigger: { trigger: '.services-grid', start: 'top 80%' }, y: 30, opacity: 0, duration: 0.6, stagger: 0.1, ease: 'power3.out', clearProps: 'all' });
});

// Particles

(function initHeroParticles() {
  const canvas = document.getElementById("heroParticles");
  const hero = document.querySelector(".hero");

  if (!canvas || !hero) return;
  if (window.matchMedia("(prefers-reduced-motion: reduce)").matches) return;

  const ctx = canvas.getContext("2d");
  let particles = [];
  let animationId = null;
  let mouse = {
    x: null,
    y: null,
    active: false
  };

  function getHeroSize() {
    return {
      width: hero.clientWidth,
      height: hero.clientHeight
    };
  }

  function resizeCanvas() {
    const { width, height } = getHeroSize();
    const dpr = Math.min(window.devicePixelRatio || 1, 2);

    canvas.width = width * dpr;
    canvas.height = height * dpr;
    canvas.style.width = width + "px";
    canvas.style.height = height + "px";

    ctx.setTransform(dpr, 0, 0, dpr, 0, 0);

    createParticles(width, height);
  }

  function createParticles(width, height) {
    const count = Math.max(36, Math.min(72, Math.floor(width / 22)));

    particles = Array.from({ length: count }, () => {
      const isGold = Math.random() > 0.28;

      return {
        x: Math.random() * width,
        y: Math.random() * height,
        vx: (Math.random() - 0.5) * 0.28,
        vy: (Math.random() - 0.5) * 0.28,
        size: Math.random() * 1.8 + 0.8,
        alpha: Math.random() * 0.45 + 0.2,
        color: isGold
          ? "212, 169, 81"
          : "79, 152, 163"
      };
    });
  }

  function drawGlow(x, y, size, color, alpha) {
    const glow = ctx.createRadialGradient(x, y, 0, x, y, size * 6);
    glow.addColorStop(0, `rgba(${color}, ${alpha})`);
    glow.addColorStop(0.4, `rgba(${color}, ${alpha * 0.28})`);
    glow.addColorStop(1, `rgba(${color}, 0)`);

    ctx.beginPath();
    ctx.fillStyle = glow;
    ctx.arc(x, y, size * 6, 0, Math.PI * 2);
    ctx.fill();
  }

  function drawParticle(p) {
    drawGlow(p.x, p.y, p.size, p.color, p.alpha * 0.35);

    ctx.beginPath();
    ctx.fillStyle = `rgba(${p.color}, ${p.alpha})`;
    ctx.arc(p.x, p.y, p.size, 0, Math.PI * 2);
    ctx.fill();
  }

  function drawConnections() {
    for (let i = 0; i < particles.length; i++) {
      for (let j = i + 1; j < particles.length; j++) {
        const a = particles[i];
        const b = particles[j];
        const dx = a.x - b.x;
        const dy = a.y - b.y;
        const dist = Math.hypot(dx, dy);

        if (dist < 95) {
          const opacity = (1 - dist / 95) * 0.08;
          ctx.beginPath();
          ctx.strokeStyle = `rgba(220, 200, 160, ${opacity})`;
          ctx.lineWidth = 0.8;
          ctx.moveTo(a.x, a.y);
          ctx.lineTo(b.x, b.y);
          ctx.stroke();
        }
      }
    }
  }

  function updateParticles(width, height) {
    for (const p of particles) {
      p.x += p.vx;
      p.y += p.vy;

      if (p.x < -20) p.x = width + 20;
      if (p.x > width + 20) p.x = -20;
      if (p.y < -20) p.y = height + 20;
      if (p.y > height + 20) p.y = -20;

      if (mouse.active && mouse.x !== null && mouse.y !== null) {
        const dx = p.x - mouse.x;
        const dy = p.y - mouse.y;
        const dist = Math.hypot(dx, dy) || 1;
        const radius = 140;

        if (dist < radius) {
          const force = (radius - dist) / radius;
          p.x += (dx / dist) * force * 0.9;
          p.y += (dy / dist) * force * 0.9;
        }
      }

      drawParticle(p);
    }
  }

  function animate() {
    const { width, height } = getHeroSize();
    ctx.clearRect(0, 0, width, height);

    updateParticles(width, height);
    drawConnections();

    animationId = requestAnimationFrame(animate);
  }

  function handleMouseMove(event) {
    const rect = hero.getBoundingClientRect();
    mouse.x = event.clientX - rect.left;
    mouse.y = event.clientY - rect.top;
    mouse.active = true;
  }

  function handleMouseLeave() {
    mouse.x = null;
    mouse.y = null;
    mouse.active = false;
  }

  hero.addEventListener("mousemove", handleMouseMove);
  hero.addEventListener("mouseleave", handleMouseLeave);
  window.addEventListener("resize", resizeCanvas);

  resizeCanvas();
  animate();
})();